version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: leetcode
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: leetcode_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "yes"]  # Enables AOF persistence
  
  judge-cpp:
     build:
         context: ./docker/judge-cpp
     image: judge-cpp:latest
     container_name: judge-cpp
     restart: on-failure 

  api: 
    build: .
    container_name: leetcode-api
    command: npm run dev 
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres
      - redis
      - judge-cpp

volumes:
  pgdata:
  redisdata:

